// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx1BtyZaVzpquatqx4-5fw8sRu44qyjlQ',
    appId: '1:665407293947:web:49b6b538cca9b87fb7a35e',
    messagingSenderId: '665407293947',
    projectId: 'gemini-chat-b896b',
    authDomain: 'gemini-chat-b896b.firebaseapp.com',
    storageBucket: 'gemini-chat-b896b.firebasestorage.app',
    measurementId: 'G-5588YBRX67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyd4i3eg7oboUaiBG4fsMZnaRuldnLaCY',
    appId: '1:665407293947:android:8887e283af56edc1b7a35e',
    messagingSenderId: '665407293947',
    projectId: 'gemini-chat-b896b',
    storageBucket: 'gemini-chat-b896b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvM-8ciXqt57wWd6nwaLivRz3Zn9vrNAo',
    appId: '1:665407293947:ios:4011e86260ac2aa0b7a35e',
    messagingSenderId: '665407293947',
    projectId: 'gemini-chat-b896b',
    storageBucket: 'gemini-chat-b896b.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvM-8ciXqt57wWd6nwaLivRz3Zn9vrNAo',
    appId: '1:665407293947:ios:4011e86260ac2aa0b7a35e',
    messagingSenderId: '665407293947',
    projectId: 'gemini-chat-b896b',
    storageBucket: 'gemini-chat-b896b.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx1BtyZaVzpquatqx4-5fw8sRu44qyjlQ',
    appId: '1:665407293947:web:9d0dd112657e3140b7a35e',
    messagingSenderId: '665407293947',
    projectId: 'gemini-chat-b896b',
    authDomain: 'gemini-chat-b896b.firebaseapp.com',
    storageBucket: 'gemini-chat-b896b.firebasestorage.app',
    measurementId: 'G-LB51WPG07B',
  );

}